services:
  vnc-forwarder:
    build: vnc-forwarder
    privileged: true
    environment:
      - STORAGE_LOCATION=/opt/storage
    volumes:
      - ./storage:/opt/storage
    ports:
      - "5900:5900"

  rdp-forwarder:
    build: rdp-forwarder
    privileged: true
    environment:
      - STORAGE_LOCATION=/opt/storage
      - GUACD_ADDR=guacd:4822
      - TARGET_ADDR=vnc-server:5901
    volumes:
      - ./storage:/opt/storage
    ports:
      - "3389:3389"

  connection-exporter:
    build: connection-exporter
    volumes:
      - ./recordings:/opt/recordings
      - ./downloads:/opt/downloads
    ports:
      - "9900:9900"

  vnc-server:
    image: consol/rocky-xfce-vnc
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - "VNC_PW=guest"

  xrdp-server:
    image: danchitnis/xrdp:ubuntu-xfce
    command:
      - guest
      - guest
      - yes
    ports:
      - "22000:22"
      - "33890:3389"

  guacd:
    image: guacamole/guacd:1.5.3
    ports:
      - "4822:4822"
    environment:
      - GUACD_LOG_LEVEL=trace
    volumes:
      - ./recordings:/opt/recordings

  guacamole-client:
    image: guacamole/guacamole:1.5.3
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=rdp-forwarder
      - GUACD_PORT=3389
      - GUACAMOLE_HOME=/etc/guacamole/
    depends_on:
      - guacd
    volumes:
      - ./configs:/etc/guacamole/
