services:
  vnc-forwarder:
    build: vnc-forwarder
    privileged: true
    environment:
      - STORAGE_LOCATION=/opt/storage
    volumes:
      - ./storage:/opt/storage
    ports:
      - "5900:5900"

  rdp-forwarder:
    build: rdp-forwarder
    privileged: true
    environment:
      - STORAGE_LOCATION=/opt/storage
    volumes:
      - ./storage:/opt/storage
    ports:
      - "3389:3389"

  # connection-exporter:
  #   build: connection-exporter
  #   volumes:
  #     - ./storage:/opt/storage
  #     - ./downloads:/opt/downloads
  #   ports:
  #     - "9900:9900"

  vnc-server:
    image: consol/rocky-xfce-vnc
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - VNC_PW=guest

  xrdp-server:
    image: danchitnis/xrdp:ubuntu-xfce
    command:
      - guest
      - guest
      - yes
    ports:
      - "22000:22"
      - "33890:3389"

  guacd:
    image: guacamole/guacd
    ports:
      - "4822:4822"
    environment:
      - GUACD_LOG_LEVEL=trace
