services:
  connection-forwarder:
    build: connection-forwarder
    environment:
      - STORAGE_LOCATION=/opt/storage
    volumes:
      - ./storage:/opt/storage
    ports:
      - "3389:3389"
  # connection-exporter:
  #   build: connection-exporter
  xrdp:
    image: frxyt/xrdp:xfce
    environment:
      - FRX_XRDP_USER_NAME=john.doe
      - FRX_XRDP_USER_PASSWORD=MyPassword
    ports:
      - "22000:22"
      #- "3389:3389"